// Code generated by generate_models_file.go, DO NOT EDIT.

package main

//go:generate go run -tags=generate_models_file . -file=constants.gen.go

const (
	RoleSystem    = "system"
	RoleAssistant = "assistant"
	RoleUser      = "user"
	RoleTool      = "tool"
)

const (
	ToolTypeFunction = "function"
)

const (
	FinishReasonToolCalls = "tool_calls"
	FinishReasonStop      = "stop"
)

const (
	ContentPartTypeText     = "text"
	ContentPartTypeImageUrl = "image_url"
)

const (
	ImageUrlDetailLow  = "low"
	ImageUrlDetailHigh = "high"
	ImageUrlDetailAuto = "auto"
)

const (
	ResponseFormatJSONObject = "json_object"
	ResponseFormatText       = "text"
)

const (
	ModelMoonshot128K = "moonshot-v1-128k"
	ModelMoonshot32K  = "moonshot-v1-32k"
	ModelMoonshot8K   = "moonshot-v1-8k"
)
